{% set version = "0.1.2" %}

package:
  name: jyg
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jyg/jyg-{{ version }}.tar.gz
  sha256: 44c9ca5a10551689598a17bbd859bbb2ea374ce82f7c30ea72ec05248c02d704

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - jupyter-jyg = jyg.jygapp:main
    - jyg = jyg.jygapp:main

requirements:
  host:
    - flit-core >=3.7.1,<4
    - pip
    - python {{ python_min }}
  run:
    - jinja2 >=3.1
    - jsonschema
    - jupyter_core >=4.7.1
    - python >={{ python_min }}

test:
  imports:
    - jyg
  commands:
    - pip check
    - jupyter-jyg --help
    - jyg --help
    - python -m jyg --help
    - jupyter labextension list
    - jupyter server extension list
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    - grep -iE "@deathbeds/jyg.*OK" labextensions
    - grep -iE "jyg.*OK" server_extensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deathbeds/jyg
  summary: run Jupyter browser client commands from a CLI, REST API, or other browser windows
  license: BSD-3-Clause
  doc_url: https://jyg.rtfd.io
  license_file:
    - LICENSE
    - src/jyg/_d/share/jupyter/labextensions/@deathbeds/jyg/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
